services:
  - type: web
    name: react-ecommerce-monolith
    env: node
    buildCommand: npm run build:monolith
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    # Alternative build approach if needed:
    # buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build
